@extends('Academy.Layouts.master')
@section('title', app()->getLocale()==='ar'?'ماسح الحضور والانصراف':'Attendance scanner')
@push('css')
<style>
.scan-page{--ink:#102a43;--muted:#64748b;--line:#e2e8f0;max-width:1000px;margin:auto}.scan-head{display:flex;align-items:center;justify-content:space-between;gap:18px;margin:22px 0}.scan-head h1{margin:0 0 5px;color:var(--ink);font-size:25px}.scan-head p{margin:0;color:var(--muted)}.scan-panel{display:grid;grid-template-columns:1fr 1fr;gap:16px}.scan-box,.scan-result{padding:22px;border:1px solid var(--line);border-radius:8px;background:#fff}.scan-box label{display:block;margin-bottom:13px;color:var(--ink);font-weight:700}.scan-box select,.scan-box input{width:100%;min-height:48px;border:1px solid var(--line);border-radius:7px;padding:10px 12px}.scan-code{font:700 16px monospace;direction:ltr;text-align:left}.scan-mode{display:flex;gap:6px;margin:12px 0}.scan-mode label{flex:1;margin:0}.scan-mode input{display:none}.scan-mode span{display:block;padding:9px;text-align:center;border:1px solid var(--line);border-radius:6px;color:var(--muted)}.scan-mode input:checked+span{border-color:#0f766e;background:#ecfdf5;color:#0f766e}.scan-submit{width:100%;min-height:48px;border:0;border-radius:7px;background:#0f766e;color:#fff;font-weight:800}.scan-hint{margin-top:12px;color:var(--muted);font-size:12px}.scan-result{display:grid;place-items:center;min-height:350px;text-align:center}.scan-result.is-success{border-color:#86efac;background:#f0fdf4}.scan-result.is-warning{border-color:#fde68a;background:#fffbeb}.scan-result.is-error{border-color:#fecaca;background:#fef2f2}.scan-result img{width:100px;height:100px;object-fit:cover;border-radius:50%;border:4px solid #fff;box-shadow:0 5px 18px #0f172a22}.scan-result h2{margin:12px 0 4px;color:var(--ink)}.scan-result p{margin:3px;color:var(--muted)}.scan-result strong{display:block;margin-top:10px;font-size:18px}.scan-empty svg{width:64px;height:64px;color:#94a3b8}.scan-log{margin-top:16px;padding:17px;border:1px solid var(--line);border-radius:8px;background:#fff}.scan-log h3{font-size:16px}.scan-log-list{display:grid;gap:7px}.scan-log-item{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px;background:#f8fafc;border-radius:6px;font-size:12px}@media(max-width:767px){.scan-head{align-items:flex-start;flex-direction:column}.scan-panel{grid-template-columns:1fr}.scan-box,.scan-result{padding:16px}.scan-result{min-height:280px}}
</style>
@endpush
@php($ar=app()->getLocale()==='ar')
@section('content')
<div class="middle-content container-xxl p-0 scan-page" dir="{{ $ar?'rtl':'ltr' }}">
 <header class="scan-head"><div><h1>{{ $ar?'ماسح الحضور والانصراف':'Attendance scanner' }}</h1><p>{{ $ar?'امسح كارت الطالب بسكانر USB أو أدخل رقم العضوية يدويًا.':'Scan a card with a USB scanner or enter the membership number.' }}</p></div><a class="btn btn-outline-secondary" href="{{ route('academy.attendance.index') }}">{{ $ar?'سجل الحضور':'Attendance records' }}</a></header>
 <div class="scan-panel">
  <form id="scanForm" class="scan-box">
   <label>{{ $ar?'جلسة اليوم':'Today session' }}<select id="sessionId" required><option value="">{{ $ar?'اختر الجلسة أو المجموعة':'Select session or group' }}</option>@foreach($sessions as $session)<option value="{{ $session->id }}">{{ $session->group?->name }} · {{ $session->starts_at??'-' }} - {{ $session->ends_at??'-' }}</option>@endforeach</select></label>
   <label>{{ $ar?'رقم العضوية / الكود':'Membership code' }}<input id="scanCode" class="scan-code" autocomplete="off" placeholder="HZ-..." required></label>
   <div class="scan-mode"><label><input type="radio" name="mode" value="auto" checked><span>{{ $ar?'تلقائي':'Auto' }}</span></label><label><input type="radio" name="mode" value="check_in"><span>{{ $ar?'دخول':'Check in' }}</span></label><label><input type="radio" name="mode" value="check_out"><span>{{ $ar?'انصراف':'Check out' }}</span></label></div>
   <button class="scan-submit">{{ $ar?'تسجيل المسح':'Record scan' }}</button>
   <p class="scan-hint">{{ $ar?'اضبط السكانر لإرسال Enter بعد قراءة الباركود. سيعود المؤشر تلقائيًا للحقل بعد كل عملية.':'Configure the scanner to send Enter after each barcode. Focus returns automatically after every scan.' }}</p>
  </form>
  <div id="scanResult" class="scan-result"><div class="scan-empty"><i data-feather="maximize"></i><h2>{{ $ar?'جاهز للمسح':'Ready to scan' }}</h2><p>{{ $ar?'اختر الجلسة ثم امسح كارت الطالب.':'Choose a session, then scan a student card.' }}</p></div></div>
 </div>
 <section class="scan-log"><h3>{{ $ar?'آخر عمليات المسح':'Recent scans' }}</h3><div id="scanLog" class="scan-log-list"><p class="text-muted">{{ $ar?'لا توجد عمليات بعد.':'No scans yet.' }}</p></div></section>
</div>
@endsection
@push('js')
<script>
document.addEventListener('DOMContentLoaded',()=>{const ar=@json($ar),form=document.getElementById('scanForm'),code=document.getElementById('scanCode'),session=document.getElementById('sessionId'),result=document.getElementById('scanResult'),log=document.getElementById('scanLog');let first=true;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 function focus(){setTimeout(()=>code.focus(),80)}session.addEventListener('change',focus);focus();
 form.addEventListener('submit',async e=>{e.preventDefault();if(!session.value)return;const value=code.value.trim();if(!value)return;code.disabled=true;
  try{const response=await fetch(@json(route('academy.attendance.scan')),{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify({code:value,session_id:session.value,mode:document.querySelector('[name=mode]:checked').value})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Scan failed');const duplicate=data.action==='duplicate',valid=data.subscription.valid;result.className='scan-result '+(duplicate||!valid?'is-warning':'is-success');const action=data.action==='check_out'?(ar?'تم تسجيل الانصراف':'Check-out recorded'):(duplicate?(ar?'تم التسجيل من قبل':'Already recorded'):(ar?'تم تسجيل الحضور':'Check-in recorded'));result.innerHTML='<div><img id="scanStudentImage" src="'+esc(data.student.image)+'"><h2>'+esc(data.student.name)+'</h2><p>'+esc(data.student.phone||'')+'</p><strong>'+esc(action)+'</strong><p>'+(valid?(ar?'الاشتراك ساري':'Subscription active'):(ar?'تنبيه: الاشتراك غير نشط أو منتهي':'Warning: subscription inactive or expired'))+'</p><p>'+(ar?'دخول: ':'In: ')+esc(data.record.check_in||'-')+' · '+(ar?'انصراف: ':'Out: ')+esc(data.record.check_out||'-')+'</p></div>';const img=document.getElementById('scanStudentImage');img.onerror=()=>{img.src=data.student.fallback};if(first){log.innerHTML='';first=false}log.insertAdjacentHTML('afterbegin','<div class="scan-log-item"><b>'+esc(data.student.name)+'</b><span>'+esc(action)+'</span><time>'+new Date().toLocaleTimeString()+'</time></div>');
  }catch(err){result.className='scan-result is-error';result.innerHTML='<div><i data-feather="x-circle"></i><h2>'+(ar?'تعذر تسجيل العملية':'Scan failed')+'</h2><p>'+esc(err.message)+'</p></div>';if(window.feather)feather.replace()}finally{code.value='';code.disabled=false;focus()}});
});
</script>
@endpush
