@extends('Academy.Layouts.master')
@section('title', $venueSpace->exists ? trans('admin.venues.edit_space') : trans('admin.venues.add_space'))
@section('content')
<div class="middle-content container-xxl p-0"><h3 class="mb-4">{{ $venueSpace->exists ? trans('admin.venues.edit_space') : trans('admin.venues.add_space') }}</h3>@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ $venueSpace->exists ? route('academy.venue-spaces.update',$venueSpace) : route('academy.venue-spaces.store') }}" class="bg-white p-4 rounded shadow-sm">@csrf @if($venueSpace->exists)@method('PUT')@endif<div class="row g-3">
<div class="col-md-6"><label class="form-label">{{ trans('admin.venues.location') }}</label><select class="form-select" name="venue_id" required>@foreach($venues as $venue)<option value="{{ $venue->id }}" @selected(old('venue_id',$venueSpace->venue_id)==$venue->id)>{{ $venue->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">{{ trans('admin.sport.sport') }}</label><select class="form-select" name="sport_id"><option value="">-</option>@foreach($sports as $sport)<option value="{{ $sport->id }}" @selected(old('sport_id',$venueSpace->sport_id)==$sport->id)>{{ $sport->name }}</option>@endforeach</select></div>
<div class="col-md-6"><label class="form-label">{{ trans('admin.venues.name_ar') }}</label><input class="form-control" name="name_ar" required value="{{ old('name_ar',$venueSpace->getTranslation('name','ar',false)) }}" dir="rtl"></div><div class="col-md-6"><label class="form-label">{{ trans('admin.venues.name_en') }}</label><input class="form-control" name="name_en" required value="{{ old('name_en',$venueSpace->getTranslation('name','en',false)) }}" dir="ltr"></div>
<div class="col-md-6"><label class="form-label">{{ trans('admin.venues.type') }}</label><select class="form-select" name="space_type">@foreach(['court','field','hall','pool','other'] as $type)<option value="{{ $type }}" @selected(old('space_type',$venueSpace->space_type)===$type)>{{ trans('admin.venues.space_types.'.$type) }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">{{ trans('admin.venues.capacity') }}</label><input type="number" min="1" class="form-control" name="capacity" value="{{ old('capacity',$venueSpace->capacity) }}"></div><div class="col-md-3"><label class="form-label">{{ trans('admin.venues.slot_minutes') }}</label><select class="form-select" name="slot_minutes">@foreach([30,45,60,90,120] as $minutes)<option value="{{ $minutes }}" @selected(old('slot_minutes',$venueSpace->slot_minutes ?: 60)==$minutes)>{{ $minutes }}</option>@endforeach</select></div>
<div class="col-md-4"><label class="form-label">{{ trans('admin.venues.hourly_price') }}</label><input type="number" min="0" step="0.01" class="form-control" name="hourly_price" required value="{{ old('hourly_price',$venueSpace->hourly_price) }}"></div><div class="col-md-4"><label class="form-label">{{ trans('admin.venues.opens_at') }}</label><input type="time" class="form-control" name="opens_at" required value="{{ old('opens_at',substr($venueSpace->opens_at ?: '08:00',0,5)) }}"></div><div class="col-md-4"><label class="form-label">{{ trans('admin.venues.closes_at') }}</label><input type="time" class="form-control" name="closes_at" required value="{{ old('closes_at',substr($venueSpace->closes_at ?: '23:00',0,5)) }}"></div>
<div class="col-12"><label class="form-label">{{ trans('admin.venues.description_ar') }}</label><textarea class="form-control" name="description_ar" dir="rtl">{{ old('description_ar',$venueSpace->getTranslation('description','ar',false)) }}</textarea></div><div class="col-12"><label class="form-label">{{ trans('admin.venues.description_en') }}</label><textarea class="form-control" name="description_en" dir="ltr">{{ old('description_en',$venueSpace->getTranslation('description','en',false)) }}</textarea></div><div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="active" value="1" @checked(old('active',$venueSpace->exists ? $venueSpace->active : true))><label class="form-check-label">{{ trans('admin.venues.active') }}</label></div></div></div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary">{{ trans('admin.submit') }}</button><a class="btn btn-light" href="{{ route('academy.venue-spaces.index') }}">{{ trans('admin.cancel') }}</a></div></form></div>
@endsection
