@extends('Academy.Layouts.master')
@php($ar = app()->getLocale()==='ar')
@section('title', $ar?'إرسال WhatsApp':'Send WhatsApp')
@push('css') @include('Academy.pages.whatsapp._styles') @endpush
@section('content')
<div class="middle-content container-xxl p-0 wa-page"><section class="wa-hero"><h1>{{ $ar?'رسالة أو حملة جديدة':'New message or campaign' }}</h1><p>{{ $ar?'اختر اللاعبين أو المدربين ثم استخدم رسالة مباشرة أو قالبًا معتمدًا.':'Select players or coaches, then use a direct message or an approved template.' }}</p></section>
@if($errors->any())<div class="wa-errors">@foreach($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div>@endif
<form class="wa-form" method="POST" action="{{ route('academy.whatsapp.send') }}">@csrf<div class="wa-form-grid">
<div class="wa-field wa-span-2"><label>{{ $ar?'اسم عملية الإرسال':'Send name' }}</label><input name="campaign_name" value="{{ old('campaign_name') }}" placeholder="{{ $ar?'مثال: تنبيه تدريب الخميس':'Example: Thursday training reminder' }}"></div>
<div class="wa-field"><label>{{ $ar?'غرض الرسالة':'Message purpose' }}</label><select name="purpose" id="message-purpose"><option value="notification">{{ $ar?'تنبيه أو رسالة تشغيلية':'Notification / operational' }}</option><option value="marketing" @selected(old('purpose')==='marketing')>{{ $ar?'رسالة تسويقية':'Marketing' }}</option></select></div>
<div class="wa-field" id="marketing-consent" hidden><label class="wa-recipient"><input type="checkbox" name="marketing_opt_in" value="1" @checked(old('marketing_opt_in'))><span>{{ $ar?'أؤكد أن المستلمين وافقوا على استقبال رسائل تسويقية عبر WhatsApp.':'I confirm recipients opted in to WhatsApp marketing.' }}</span></label></div>
<div class="wa-field wa-span-2"><div class="d-flex justify-content-between align-items-center mb-2"><label class="m-0">{{ $ar?'المستلمون — حتى 50 في العملية الواحدة':'Recipients — up to 50 per send' }}</label><div><button type="button" class="btn btn-sm btn-outline-success" data-select="all">{{ $ar?'أول 50':'First 50' }}</button> <button type="button" class="btn btn-sm btn-outline-secondary" data-select="none">{{ $ar?'إلغاء':'Clear' }}</button></div></div><div class="wa-recipient-list">
@foreach($recipientStudents as $student)<label class="wa-recipient"><input type="checkbox" name="recipients[]" value="student:{{ $student->id }}" @checked(in_array('student:'.$student->id,old('recipients',$selectedRecipients)))><span><strong>{{ $student->name }}</strong><small>{{ $ar?'لاعب':'Player' }} · {{ $student->phone ?: $student->guardian_phone }}</small></span></label>@endforeach
@foreach($recipientCoaches as $coach)<label class="wa-recipient"><input type="checkbox" name="recipients[]" value="coach:{{ $coach->id }}" @checked(in_array('coach:'.$coach->id,old('recipients',$selectedRecipients)))><span><strong>{{ $coach->name }}</strong><small>{{ $ar?'مدرب':'Coach' }} · {{ $coach->phone }}</small></span></label>@endforeach
</div></div>
<div class="wa-field"><label>{{ $ar?'نوع الرسالة':'Message type' }}</label><select name="message_type" id="message-type"><option value="template">{{ $ar?'قالب Meta معتمد — للتنبيهات والتسويق':'Approved Meta template — notifications & marketing' }}</option><option value="text" @selected(old('message_type')==='text')>{{ $ar?'رسالة نصية — للمحادثات المفتوحة فقط':'Text — open conversations only' }}</option></select></div>
<div class="wa-field template-field"><label>{{ $ar?'لغة القالب':'Template language' }}</label><select name="template_language"><option value="ar">العربية</option><option value="en_US">English</option></select></div>
<div class="wa-field wa-span-2 template-field"><label>{{ $ar?'اسم القالب المعتمد في Meta':'Approved Meta template name' }}</label><input name="template_name" value="{{ old('template_name') }}" placeholder="training_reminder"><small>{{ $ar?'يجب أن يطابق الاسم المعتمد في WhatsApp Manager.':'Must exactly match the approved WhatsApp Manager template.' }}</small></div>
<div class="wa-field wa-span-2 template-field"><label>{{ $ar?'قيم متغيرات القالب':'Template body variables' }}</label><textarea name="template_parameters" placeholder="{{ $ar?'قيمة المتغير 1&#10;قيمة المتغير 2 — كل قيمة في سطر':'Variable 1 value&#10;Variable 2 value — one per line' }}">{{ old('template_parameters') }}</textarea><small>{{ $ar?'اتركها فارغة إذا كان القالب بلا متغيرات. استخدم {name} لاسم المستلم و{phone} لرقمه.':'Leave empty when unused. Use {name} for recipient name and {phone} for phone.' }}</small></div>
<div class="wa-field wa-span-2 text-field" hidden><label>{{ $ar?'نص الرسالة':'Message text' }}</label><textarea name="body" placeholder="{{ $ar?'اكتب الرسالة...':'Write the message...' }}">{{ old('body') }}</textarea></div>
</div><div class="wa-toolbar"><button type="submit" class="wa-btn wa-btn-primary"><i class="fa-brands fa-whatsapp"></i>{{ $ar?'إرسال الآن':'Send now' }}</button><a class="wa-btn wa-btn-outline" href="{{ route('academy.whatsapp.index') }}">{{ $ar?'إلغاء':'Cancel' }}</a></div></form></div>
@endsection
@push('js')<script>document.addEventListener('DOMContentLoaded',()=>{const type=document.getElementById('message-type'),purpose=document.getElementById('message-purpose'),toggle=()=>{if(purpose.value==='marketing')type.value='template';document.querySelectorAll('.template-field').forEach(x=>x.hidden=type.value!=='template');document.querySelectorAll('.text-field').forEach(x=>x.hidden=type.value!=='text');document.getElementById('marketing-consent').hidden=purpose.value!=='marketing'};type.addEventListener('change',toggle);purpose.addEventListener('change',toggle);toggle();document.querySelectorAll('[data-select]').forEach(b=>b.addEventListener('click',()=>{const boxes=[...document.querySelectorAll('input[name="recipients[]"]')];boxes.forEach((x,i)=>x.checked=b.dataset.select==='all'&&i<50)}));const form=document.querySelector('.wa-form');form.addEventListener('submit',()=>{const button=form.querySelector('button[type="submit"]');if(button){button.disabled=true;button.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i>'}});});</script>@endpush
