@extends('Academy.Layouts.master')
@section('title', $venue->exists ? trans('admin.venues.edit_location') : trans('admin.venues.add_location'))
@section('content')
<div class="middle-content container-xxl p-0"><div class="mb-4"><h3>{{ $venue->exists ? trans('admin.venues.edit_location') : trans('admin.venues.add_location') }}</h3></div>
@if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ $venue->exists ? route('academy.venues.update',$venue) : route('academy.venues.store') }}" class="bg-white p-4 rounded shadow-sm">@csrf @if($venue->exists)@method('PUT')@endif
<div class="row g-3"><div class="col-md-6"><label class="form-label">{{ trans('admin.venues.name_ar') }}</label><input class="form-control" name="name_ar" required value="{{ old('name_ar',$venue->getTranslation('name','ar',false)) }}" dir="rtl"></div><div class="col-md-6"><label class="form-label">{{ trans('admin.venues.name_en') }}</label><input class="form-control" name="name_en" required value="{{ old('name_en',$venue->getTranslation('name','en',false)) }}" dir="ltr"></div>
<div class="col-md-6"><label class="form-label">{{ trans('admin.venues.phone') }}</label><input class="form-control" name="phone" value="{{ old('phone',$venue->phone) }}"></div><div class="col-md-6"><label class="form-label">{{ trans('admin.venues.address') }}</label><input class="form-control" name="address" required value="{{ old('address',$venue->address) }}"></div>
<div class="col-md-6"><label class="form-label">{{ trans('admin.venues.timezone') }}</label><select class="form-select" name="timezone"><option value="Africa/Cairo" @selected(old('timezone',$venue->timezone)==='Africa/Cairo')>Africa/Cairo</option><option value="Asia/Qatar" @selected(old('timezone',$venue->timezone)==='Asia/Qatar')>Asia/Qatar</option><option value="Asia/Riyadh" @selected(old('timezone',$venue->timezone)==='Asia/Riyadh')>Asia/Riyadh</option><option value="Asia/Dubai" @selected(old('timezone',$venue->timezone)==='Asia/Dubai')>Asia/Dubai</option></select></div>
<div class="col-md-3"><label class="form-label">{{ trans('admin.venues.currency') }}</label><select class="form-select" name="currency">@foreach(['EGP','QAR','SAR','AED'] as $currency)<option @selected(old('currency',$venue->currency ?: 'EGP')===$currency)>{{ $currency }}</option>@endforeach</select></div><div class="col-md-3 d-flex align-items-end"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" name="active" value="1" @checked(old('active',$venue->exists ? $venue->active : true))><label class="form-check-label">{{ trans('admin.venues.active') }}</label></div></div></div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary"><i class="fa-solid fa-floppy-disk me-1"></i>{{ trans('admin.submit') }}</button><a class="btn btn-light" href="{{ route('academy.venues.index') }}">{{ trans('admin.cancel') }}</a></div></form></div>
@endsection
