name: API-Laravel-CI/CD
 
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-cicd:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'

      # - uses: actions/checkout@v3

      # - name: Copy .env
      #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # - name: Install Dependencies
      #   run: composer update

      # - name: Generate key
      #   run: php artisan key:generate

      # - name: Directory Permissions
      #   run: chmod -R 777 storage bootstrap/cache
      
      # - name: Execute tests (Unit and Feature tests) via PHPUnit
      #   env:
      #    DB_CONNECTION: mysql
      #    DB_HOST: ${{ secrets.DB_HOST_D }}
      #    DB_DATABASE: ${{ secrets.DB_DATABASE_D }}
      #    DB_USERNAME: ${{ secrets.DB_USERNAME_D }}
      #    DB_PASSWORD: ${{ secrets.DB_PASSWORD_D }}
      #   run: vendor/bin/phpunit

  deploy-ec2s:
    runs-on: ubuntu-latest
    needs: build-cicd
    steps:
      - name: SSH Deploy-Test 
# ${{ success() }} && 
        if: ( github.event_name == 'push' ||  github.event_name == 'pull_request' ) && github.ref == 'refs/heads/master' 

        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            echo "CH-Dir"
            cd ${{ secrets.REMOTE_PATH }}
            source ~/script
            echo "Pull"
            sudo git pull origin master
            echo "Update Composer"
            yes | sudo composer update
            echo "Optimize Cach"
            sudo php artisan optimize:clear
            echo "Migrate DB"
            sudo php artisan migrate --force
        
      
      - name:  Deploy Develop
        
        if: ( github.event_name == 'push' ||  github.event_name == 'pull_request' ) && github.ref == 'refs/heads/develop' 
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.REMOTE_HOST_D }}
           username: ${{ secrets.REMOTE_USERNAME }}
           key: ${{ secrets.REMOTE_SSH_KEY_D }}
           script: |
            echo "DEVELOP"
